---
version: "3"
services:
 devopsdb:
   image: achyuty/java_app:db
   ports:
     - "3306:3306"

 application:
   image: achyuty/java_app:app
   ports:
     - "2222:8080"
   depends_on:
     - "devopsdb"
